# Configuración de la DB en AWS
spring.datasource.url=jdbc:postgresql://chat-db-instancia.c7umq4qk6j9k.us-east-2.rds.amazonaws.com:5432/chat
spring.datasource.username=postgres
spring.datasource.password=PabloYJose6423
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Datos de tu captura de AWS
aws.cognito.userPoolId=us-east-2_lwuLHjhn6
aws.cognito.region=us-east-2
# Necesitarás el Client ID que se genera al crear la "App Client" en Cognito
aws.cognito.clientId=4nqgols7h3t8bgqk3hjspet8m0
aws.cognito.clientSecret=1224p1cpqgqpcqn3b509ofqk195t0m9h7uj67jg9eoimdn10usfo

# Deshabilitar el login por defecto de Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# El issuer es la URL de tu User Pool
# Formato: https://cognito-idp.<region>.amazonaws.com/<user_pool_id>
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_IwuLHjhn6